const DEFAULT_PORT = 3000;
const ROOT_NODE_ADDRESS = 'http://localhost3000';
const WALLET_INFO_PATH = '/api/wallet-info';
const WALLET_INFO_URI = `${ROOT_NODE_ADDRESS}${WALLET_INFO_PATH}`;
const TRANSACT_PATH = '/api/transact';
const TRANSACT_URI = `${ROOT_NODE_ADDRESS}${TRANSACT_PATH}`;
const TRANSACTION_POOL_MAP_PATH = '/api/transaction-pool-map';
const TRANSACTION_POOL_MAP_URI = `${ROOT_NODE_ADDRESS}${TRANSACTION_POOL_MAP_PATH}`;
const MINE_TRANSACTIONS_PATH = '/api/mine-transactions';

module.exports = {
  DEFAULT_PORT,
  ROOT_NODE_ADDRESS,
  TRANSACT_PATH,
  TRANSACT_URI,
  TRANSACTION_POOL_MAP_PATH,
  TRANSACTION_POOL_MAP_URI,
  WALLET_INFO_PATH,
  WALLET_INFO_URI,
  MINE_TRANSACTIONS_PATH,
};
