const DEFAULT_PORT = 3000;
const ROOT_NODE_ADDRESS = `http://localhost:${DEFAULT_PORT}`;
const WALLET_INFO_LINK = '/api/wallet-info';
const WALLET_INFO_URI = `${ROOT_NODE_ADDRESS}${WALLET_INFO_LINK}`;
const TRANSACTION_POOL_MAP_LINK = '/api/transaction-pool-map';
const TRANSACTION_POOL_MAP_URI = `${ROOT_NODE_ADDRESS}${TRANSACTION_POOL_MAP_LINK}`;

module.exports = {
  DEFAULT_PORT,
  ROOT_NODE_ADDRESS,
  TRANSACTION_POOL_MAP_LINK,
  TRANSACTION_POOL_MAP_URI,
  WALLET_INFO_LINK,
  WALLET_INFO_URI,
};
